### ISSUE TITLE
# This translates the website to the preferred language.

### ISSUE THREAD

**Issue by UofTGroup3** [UofTGroup3/toronto-newcomers-guide#4]
## User Story:
>**As a newcomer to the GTA**,
>*I want* to easily find essential places, services, transportation and organizations,
>*so that* I can smoothly transition and adapt to my new environment.

### Given I need information in a different language,
*When I* select my preferred language,
*Then* the site's content should be translated using the Google Translate API.

**Comment by EhsanAsh** [comment]
This issue is done and completed by Milena
