### ISSUE TITLE
# This creates "essential places" section.

### ISSUE THREAD

**Issue by UofTGroup3** [UofTGroup3/toronto-newcomers-guide#8]
## User Story:
>**As a newcomer to the GTA**,
>*I want* to easily find essential places, services, transportation and organizations,
>*so that* I can smoothly transition and adapt to my new environment.

### Given I am looking for essential places,
*When I* navigate to the Essential Places section,
*Then I* should find links and instructions to essential places and related information.

**Comment by EhsanAsh** [comment]
Katrina has completed this issue. Excellent job
